#!/usr/bin/env bash
# User-level NVIDIA EGL/Vulkan runtime setup for headless SimplerEnv runs.
#
# This script downloads NVIDIA graphics runtime debs, extracts the required
# libraries into a user-writable directory, and generates a setup_env.sh file.
# It does not require sudo and does not modify ~/.bashrc by default.
#
# Usage:
#   bash examples/SimplerEnv/setup_nvidia_graphics.sh
#   source "$HOME/.cache/resvla_nvidia_graphics/setup_env.sh"
#
# Optional:
#   NVIDIA_GRAPHICS_PREFIX=/path/to/runtime bash examples/SimplerEnv/setup_nvidia_graphics.sh
#   NVIDIA_DRIVER_MAJOR=550 bash examples/SimplerEnv/setup_nvidia_graphics.sh
#   NVIDIA_PACKAGE_VERSION=550.144.03-0ubuntu1 bash examples/SimplerEnv/setup_nvidia_graphics.sh
#   NVIDIA_GRAPHICS_UPDATE_BASHRC=1 bash examples/SimplerEnv/setup_nvidia_graphics.sh

set -euo pipefail

PREFIX="${NVIDIA_GRAPHICS_PREFIX:-${HOME}/.cache/resvla_nvidia_graphics}"
DRIVER_MAJOR="${NVIDIA_DRIVER_MAJOR:-}"
PACKAGE_VERSION="${NVIDIA_PACKAGE_VERSION:-}"
UPDATE_BASHRC="${NVIDIA_GRAPHICS_UPDATE_BASHRC:-0}"

LIBS_DIR="${PREFIX}/libs"
EGL_CFG_DIR="${PREFIX}/egl_config"
VK_CFG_DIR="${PREFIX}/vulkan_config"
DEB_DIR="${PREFIX}/deb_download"
EXTRACT_DIR="${DEB_DIR}/extracted"
BINS_DIR="${PREFIX}/bin"
ENV_SCRIPT="${PREFIX}/setup_env.sh"

log() { printf '[INFO] %s\n' "$*"; }
warn() { printf '[WARN] %s\n' "$*" >&2; }
die() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }

detect_driver_major() {
    if [ -n "${DRIVER_MAJOR}" ]; then
        printf '%s\n' "${DRIVER_MAJOR}"
        return
    fi

    if command -v nvidia-smi >/dev/null 2>&1; then
        local version
        version="$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -n 1 || true)"
        if [ -n "${version}" ]; then
            printf '%s\n' "${version%%.*}"
            return
        fi
    fi

    die "Could not detect NVIDIA driver major version. Set NVIDIA_DRIVER_MAJOR=550, for example."
}

download_deb() {
    local pkg="$1"
    local version="${2:-}"
    local pattern

    if [ -n "${version}" ]; then
        pattern="${pkg}_${version}*.deb"
    else
        pattern="${pkg}_*.deb"
    fi

    if compgen -G "${DEB_DIR}/${pattern}" >/dev/null; then
        log "Already downloaded: ${pkg}"
        return
    fi

    log "Downloading: ${pkg}${version:+=${version}}"
    (
        cd "${DEB_DIR}"
        if [ -n "${version}" ]; then
            apt-get download "${pkg}=${version}"
        else
            apt-get download "${pkg}"
        fi
    ) || die "Failed to download ${pkg}. Check apt sources or set NVIDIA_DRIVER_MAJOR/NVIDIA_PACKAGE_VERSION."
}

copy_if_exists() {
    local src_glob="$1"
    local dst="$2"
    mkdir -p "${dst}"
    compgen -G "${src_glob}" >/dev/null || return 0
    cp -Pn ${src_glob} "${dst}/" 2>/dev/null || true
}

DRIVER_MAJOR="$(detect_driver_major)"
log "Using NVIDIA driver package major: ${DRIVER_MAJOR}"
log "Install prefix: ${PREFIX}"

mkdir -p "${LIBS_DIR}" "${EGL_CFG_DIR}" "${VK_CFG_DIR}" "${DEB_DIR}" "${BINS_DIR}" "${EXTRACT_DIR}"

if [ -n "$(find "${LIBS_DIR}" -maxdepth 1 -name 'libEGL_nvidia.so*' -print -quit 2>/dev/null)" ] \
   && [ -f "${ENV_SCRIPT}" ]; then
    warn "Existing runtime found. Reusing: ${ENV_SCRIPT}"
    printf 'source %q\n' "${ENV_SCRIPT}"
    exit 0
fi

NVIDIA_VERSION_ARG=""
if [ -n "${PACKAGE_VERSION}" ]; then
    NVIDIA_VERSION_ARG="${PACKAGE_VERSION}"
fi

download_deb "libnvidia-gl-${DRIVER_MAJOR}" "${NVIDIA_VERSION_ARG}"
download_deb "libnvidia-extra-${DRIVER_MAJOR}" "${NVIDIA_VERSION_ARG}"
download_deb "libvulkan1"
download_deb "vulkan-tools"
download_deb "libglvnd0"
download_deb "libegl1"

log "Extracting deb packages..."
rm -rf "${EXTRACT_DIR}"
mkdir -p "${EXTRACT_DIR}"
for deb in "${DEB_DIR}"/*.deb; do
    dpkg-deb -x "${deb}" "${EXTRACT_DIR}"
done

log "Copying libraries..."
copy_if_exists "${EXTRACT_DIR}/usr/lib/x86_64-linux-gnu/*.so*" "${LIBS_DIR}"
copy_if_exists "${EXTRACT_DIR}/usr/lib/x86_64-linux-gnu/gbm/*" "${LIBS_DIR}/gbm"
copy_if_exists "${EXTRACT_DIR}/usr/lib/x86_64-linux-gnu/vdpau/*" "${LIBS_DIR}/vdpau"
copy_if_exists "${EXTRACT_DIR}/usr/bin/*" "${BINS_DIR}"

[ -f "${LIBS_DIR}/libEGL_nvidia.so.0" ] || die "libEGL_nvidia.so.0 was not found after extraction."
[ -f "${LIBS_DIR}/libGLX_nvidia.so.0" ] || die "libGLX_nvidia.so.0 was not found after extraction."

log "Writing EGL/Vulkan ICD files..."
cat > "${EGL_CFG_DIR}/10_nvidia.json" <<EOF
{
    "file_format_version": "1.0.0",
    "ICD": {
        "library_path": "${LIBS_DIR}/libEGL_nvidia.so.0"
    }
}
EOF

cat > "${VK_CFG_DIR}/nvidia_icd.json" <<EOF
{
    "file_format_version": "1.0.0",
    "ICD": {
        "library_path": "${LIBS_DIR}/libGLX_nvidia.so.0",
        "api_version": "1.3.0"
    }
}
EOF

log "Writing environment script..."
cat > "${ENV_SCRIPT}" <<EOF
# Generated by examples/SimplerEnv/setup_nvidia_graphics.sh
# Usage: source "${ENV_SCRIPT}"

export LD_LIBRARY_PATH="${LIBS_DIR}:\${LD_LIBRARY_PATH:-}"
export PATH="${BINS_DIR}:\${PATH:-}"
export __EGL_VENDOR_LIBRARY_DIRS="${EGL_CFG_DIR}"
export VK_ICD_FILENAMES="${VK_CFG_DIR}/nvidia_icd.json"
export EGL_PLATFORM=device

export XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-/tmp/resvla-nvidia-runtime-\$(id -u)}"
mkdir -p "\${XDG_RUNTIME_DIR}" && chmod 700 "\${XDG_RUNTIME_DIR}" 2>/dev/null || true
EOF
chmod +x "${ENV_SCRIPT}"

if [ "${UPDATE_BASHRC}" = "1" ]; then
    bashrc_line="source ${ENV_SCRIPT}"
    if ! grep -qF "${bashrc_line}" "${HOME}/.bashrc" 2>/dev/null; then
        {
            printf '\n# ResVLA/SimplerEnv user-level NVIDIA graphics runtime\n'
            printf '%s\n' "${bashrc_line}"
        } >> "${HOME}/.bashrc"
        log "Appended setup_env.sh to ~/.bashrc"
    fi
fi

log "Done."
log "Run this before SimplerEnv evaluation:"
printf 'source %q\n' "${ENV_SCRIPT}"
log "Optional checks:"
cat <<EOF
vulkaninfo --summary 2>&1 | grep -E "deviceName|driverVersion|apiVersion"
python - <<'PY'
import ctypes
ctypes.CDLL("libEGL_nvidia.so.0")
print("EGL OK")
PY
EOF
